builds:
  - main: main.go
    binary: system-profile-metrics
    goos:
      #-android
      - darwin
      - dragonfly
      - freebsd
      - linux
      - netbsd
      #- openbsd # TODO: fix up gopsutil to not require CGO
      #- plan9
      - solaris
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      
archive:
  format: tar.gz
  replacements:
    darwin: macOS
  files:
    - LICENSE.txt
    - README.md
    - CHANGELOG.md

release:
  draft: true
  prerelease: true

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  #name_template: "{{.ProjectName}}-v{{.Version}}"
